name: eyespot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.2.9
  smooth_page_indicator: ^1.1.0
  
  
  # core packages
  camera: ^0.10.5+9  # For camera access
  gallery_saver: ^2.0.1
  image: ^3.2.0  # For image manipulation

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  firebase_storage: ^11.6.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.3.0
  image_picker: ^0.8.5+3
  http: ^0.13.6
  dio: ^5.4.1
  http_parser: ^4.0.2




  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/fonts/
    - assets/model/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
